name: Wiki

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Setup .NET
              uses: actions/setup-dotnet@v4

            - name: Build
              run: dotnet build

            - run: |
                mkdir "Documentation"
                echo "$(dotnet run --project "./ThunderPipe/ThunderPipe.csproj" -- --help)" >> "Documentation/test.md"
            # Additional steps to generate documentation in "Documentation" directory
            - name: Upload Documentation to Wiki
              uses: SwiftDocOrg/github-wiki-publish-action@v1
              with:
                  path: "Documentation"
              env:
                  GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.WIKI_PAGES_UPLOAD_TOKEN }}
